city: On-line
year: 2020
conference_dates: November 15 - 20<sup>th</sup> 2020
venue_url: https://2020.splashcon.org/room/splash-2020-venue-rebase
#past_editions:
#  - 2018
#  - 2017
#  - 2016
#  - 2015

# Possible states for cfp and registration: hidden, inactive,
# active and sold_out (for registration only). cfp_date
# and registration_date is displayed below the button if
# present and the state is set to inactive
cfp: hidden
cfp_date: Feb 20th
cfp_form: https://docs.google.com/forms/d/e/1FAIpQLSf4-GLOcJwqmJBv4vk7WzLIziXZDn6hHmbBaShqJ85SsHeptQ/viewform?usp=sf_link
registration: hidden # active, inactive, hidden
registration_url: https://2020.splashcon.org/attending/Registration
registration_date: Open

# Control different sections on the HP
show_about: true
show_organizers: true
show_schedule: false
show_sponsors: true
show_stream: false
show_talks: true

# Footer contact details. Comment out to hide
footer_email: krikava@gmail.com
#footer_twitter: rebase_conf

featured_speakers:
- lars_bak

# Liquid can't create arrays
empty_array: []
