city: On-Line
year: 2021
conference_dates: July 11<sup>th</sup> 2021
venue_url: https://2021.ecoop.org/venue/ecoop-issta-2021-venue
past_editions:
  - 2020
#  - 2017
#  - 2016
#  - 2015

# Possible states for cfp and registration: hidden, inactive,
# active and sold_out (for registration only). cfp_date
# and registration_date is displayed below the button if
# present and the state is set to inactive
cfp: active
cfp_date: Feb 20th
cfp_form: https://docs.google.com/forms/d/e/1FAIpQLSfSJA-U_sXBXCOK6nDwx5964Qx4LkW7D1krOnno2fTEciMW5w/viewform
registration: hidden # active, inactive, hidden
registration_url:
registration_date: Open

# Control different sections on the HP
show_about: true
show_organizers: true
show_schedule: false
show_sponsors: false
show_stream: false
show_talks: false

# Footer contact details. Comment out to hide
footer_email: rebaseconf@gmail.com
footer_twitter: rebase_conf

featured_speakers:
- lars_bak

# Liquid can't create arrays
empty_array: []
